require('mgoldschmidt.basics')
require('mgoldschmidt.packer')
require('mgoldschmidt.coc-config')
require('mgoldschmidt.telescope-config')
require('mgoldschmidt.keymaps')
require('mgoldschmidt.commands')
require('mgoldschmidt.tree')
require('mgoldschmidt.jester')
